ratslam_view_template:
  ros__parameters:
    image_crop_y_max: 150
    template_x_size: 60
    template_y_size: 10
    vt_match_threshold: 0.054
    vt_panoramic: 1
    # vt_normalisation: 0
    vt_patch_normalisation: 2
    # draw
    enable: true
    vt_window_width: 640
    vt_window_height: 900

ratslam_pose_cells:
  ros__parameters:
    pc_dim_xy: 30
    pc_vt_inject_energy: 0.2
    pc_cell_x_size: 1.0
    exp_delta_pc_threshold: 2.0
    vt_active_decay: 1.0
    # draw
    enable: true

ratslam_experience_map:
  ros__parameters:
    exp_loops: 100
    # draw
    enable: true