ratslam_lv:
  ros__parameters:
    template_x_size: 60
    template_y_size: 10
    vt_match_threshold: 0.054
    vt_panoramic: 1
    vt_patch_normalise: 2
    # draw
    enable: true
    vt_window_width: 640
    vt_window_height: 900

ratslam_pc:
  ros__parameters:
    pc_dim_xy: 30
    pc_vt_inject_energy: 0.2
    pc_cell_x_size: 1.0
    # draw
    enable: true

ratslam_em:
  ros__parameters:
    exp_loops: 100
    # draw
    enable: true